services:
  mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    command: --default-time-zone=+00:00
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: shortlink-redis
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build: ./src/management-service        # Dockerfile 있는 경로
    container_name: shortlink-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data: