apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- management-service-deployment.yaml
- management-service-service.yaml
- redirect-service-deployment.yaml
- redirect-service-service.yaml
- redirect-service-sa.yaml
- ingress-with-origin-verify.yaml
- athena-batch-sa.yaml
- athena-batch-cronjob.yaml
- athena-batch-configmap.yaml
- cluster-secret-store.yaml
- hpa.yaml
images:
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newTag: f39a315ec0889d99fc709fb3b74fece28ad065cf
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newTag: c474b859c9dbae83f5a698b2c223017b062bf150
