apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- management-service-deployment.yaml
- management-service-service.yaml
- redirect-service-deployment.yaml
- redirect-service-service.yaml
- redirect-service-sa.yaml
- ingress-with-origin-verify.yaml
- athena-batch-sa.yaml
- athena-batch-cronjob.yaml
- athena-batch-configmap.yaml
images:
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newTag: dd83fbb60568469cd4bcacb23702b67164d40e54
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newTag: 603d6812c4e38c9edb7884ed2e182c338439aa4b
