apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- management-service-deployment.yaml
- management-service-service.yaml
- redirect-service-deployment.yaml
- redirect-service-service.yaml
- redirect-service-sa.yaml
- ingress-with-origin-verify.yaml
- cluster-secret-store.yaml
images:
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/management-service
  newTag: d4c45fe364084d29cc01d262c369e1d6ff6d2da0
- name: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newName: 834922934330.dkr.ecr.ap-southeast-1.amazonaws.com/redirect-service
  newTag: d4c45fe364084d29cc01d262c369e1d6ff6d2da0
