apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snipy-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Team-likelion-2nd-Project/likelion-devops-7th-team03.git
    targetRevision: develop
    path: infra/argocd/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true